# Generated by Django 4.2 on 2023-04-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='username',
            new_name='name',
        ),
    ]
