# Generated by Django 4.2 on 2023-04-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_rename_username_useraccount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
    ]
